import { vi } from 'vitest'

/** A complete vi.fn() double of ./api, shared by the GHG feature tests. */
export const listOrganizations = vi.fn()
export const getOrganization = vi.fn()
export const createOrganization = vi.fn()
export const updateOrganization = vi.fn()
export const deleteOrganization = vi.fn()
export const listFacilities = vi.fn()
export const createFacility = vi.fn()
export const updateFacility = vi.fn()
export const deleteFacility = vi.fn()
export const listEmissionFactors = vi.fn()
export const listUnits = vi.fn()
export const listActivities = vi.fn()
export const createActivity = vi.fn()
export const updateActivity = vi.fn()
export const deleteActivity = vi.fn()
export const listInventories = vi.fn()
export const getInventory = vi.fn()
export const createInventory = vi.fn()
export const updateInventory = vi.fn()
export const deleteInventory = vi.fn()
export const getBoundary = vi.fn()
export const setBoundaryTreatment = vi.fn()
export const removeBoundaryTreatment = vi.fn()
export const listAssignments = vi.fn()
export const syncAssignments = vi.fn()
export const classifyAssignment = vi.fn()
export const excludeAssignment = vi.fn()
export const includeAssignment = vi.fn()
export const getValidation = vi.fn()
export const listRuns = vi.fn()
export const executeRun = vi.fn()
export const getRun = vi.fn()
export const finalizeRun = vi.fn()
export const deleteRun = vi.fn()
