/**
 * Every screen string the UI projections use, in one place. Lint checks that
 * each value appears verbatim in frontend/src, so a renamed button fails
 * `make qa-lint` before it fails a run, and the exported procedures quote the
 * product rather than a memory of it.
 */
export const S = {
  nav: {
    landing: 'CarbonOS',
    signIn: 'Sign in',
    ghg: 'GHG accounting',
    administration: 'Administration',
    dashboard: 'Dashboard',
    accessRequests: 'Access requests',
    users: 'Users',
    platformSettings: 'Platform settings',
    editProfile: 'Edit profile',
    help: 'Help',
    forgotPassword: 'Forgot your password?',
  },
  button: {
    signIn: 'Sign in',
    signOut: 'Sign out',
    requestAccess: 'Request access',
    addUser: 'Add user',
    edit: 'Edit',
    disable: 'Disable',
    enable: 'Enable',
    delete: 'Delete',
    deleteUser: 'Delete user',
    resetPassword: 'Reset password',
    sendResetLink: 'Send reset link',
    approve: 'Approve',
    saveSettings: 'Save settings',
    saveChanges: 'Save changes',
    changePassword: 'Change password',
    setPasswordAndSignIn: 'Set password and sign in',
    setNewPassword: 'Set new password',
    newOrganization: 'New organization',
    cancel: 'Cancel',
  },
  field: {
    email: 'Email',
    password: 'Password',
    workEmail: 'Work email',
    fullName: 'Full name',
    company: 'Company (optional)',
    displayName: 'Display name',
    role: 'Role',
    status: 'Status',
    temporaryPassword: 'Temporary password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    currentPassword: 'Current password',
    confirmNewPassword: 'Confirm new password',
    supportAccessLasts: 'Support access lasts',
    whoMayCreate: 'Who may create an organization',
    editionsInside: 'Editions inside a published period',
    reason: 'Reason for this change',
  },
  option: {
    role: { ADMIN: 'Admin', MEMBER: 'Member' } as Record<string, string>,
    status: { ACTIVE: 'Active', DISABLED: 'Disabled', PENDING: 'Pending activation' } as Record<string, string>,
    organizationCreation: { EVERYONE: 'Everyone signed in', ADMINISTRATORS: 'Administrators only' } as Record<
      string,
      string
    >,
    accessOutcome: {
      APPROVED: 'Approved, waiting for the password to be set',
      COMPLETED: 'Approved, account active',
      DENIED: 'Denied',
    } as Record<string, string>,
    editions: {
      BLOCKED: 'Blocked (default)',
      ALLOWED: 'Allowed: published runs keep their factors',
    } as Record<string, string>,
  },
  dialog: {
    addUser: 'Add user',
    requestAccess: 'Request access',
  },
  heading: {
    everyChange: 'Every change',
    waitingForADecision: 'Waiting for a decision',
    alreadyDecided: 'Already decided',
    platformOverview: 'Platform overview',
    setYourPassword: 'Set your password',
    chooseANewPassword: 'Choose a new password',
    resetYourPassword: 'Reset your password',
  },
  tile: {
    users: 'Users',
    organizations: 'Organizations',
    editions: 'Factor pack editions',
    openNotices: 'Open adoption notices',
  },
  text: {
    noPendingRequests: 'No pending requests.',
    noOrganizationsYet: 'No organizations yet',
    createYourFirst: 'Create your first reporting organization to start the GHG Protocol workflow.',
    notAMember: 'You are not a member of any organization yet. Ask an owner to add you, or a platform administrator.',
    resetLinkOnItsWay: 'belongs to an active CarbonOS account, a reset link is on its way. The link is valid for 1 hour and works once.',
    setupLinkInvalid: 'This link is invalid or has expired.',
    askForANewLink: 'Ask for a new link and use the latest email.',
    passwordIsReset: 'Your password is reset. Sign in with your new password.',
    passwordChanged: 'Password changed. Your other sessions are signed out.',
    settingsSaved: 'Platform settings saved.',
    profileUpdated: 'Profile updated',
    accessRequest: 'access request',
    thanks: 'Thanks,',
  },
  org: {
    sections: {
      overview: 'Overview',
      entities: 'Legal entities',
      facilities: 'Facilities',
      factors: 'Emission factors',
      units: 'Units',
      settings: 'Settings',
      activity: 'Activity data',
      documents: 'Source documents',
      inventories: 'Inventories',
    },
    button: {
      createOrganization: 'Create organization',
      createAnyway: 'Create anyway',
      saveDetails: 'Save details',
      saveAnyway: 'Save anyway',
      saveChanges: 'Save changes',
      deleteOrganization: 'Delete organization',
      addMember: 'Add member',
      addEntity: 'Add entity',
      addFacility: 'Add facility',
      emissionSources: 'Emission sources',
      addEmissionSource: 'Add emission source',
      defineUnit: 'Define unit',
      recordDensity: 'Record density',
      addFactor: 'Add factor',
      importPack: 'Import pack',
      approve: 'Approve',
      retire: 'Retire…',
      retireFactor: 'Retire factor',
      remove: 'Remove',
      edit: 'Edit',
    },
    field: {
      name: 'Name',
      memberEmail: 'Email of an existing account',
      role: 'Role',
      reason: 'Reason',
      relationship: 'Relationship',
      economicInterest: 'Economic interest (%)',
      legalOwnership: 'Legal ownership (%)',
      operatedByCompany: 'Operated by the company',
      heldThrough: 'Held through',
      heldDirectly: 'Held directly by the reporting company',
      acquiredOn: 'Acquired on (optional)',
      disposedOn: 'Disposed of on (optional)',
      jurisdiction: 'Jurisdiction (optional)',
      location: 'Location',
      country: 'Country (optional)',
      gridRegion: 'Grid region (optional)',
      lease: 'Lease (optional)',
      leaseFrom: 'Lease from (optional)',
      leaseUntil: 'Lease until (optional)',
      legalEntity: 'Legal entity',
      sourceName: 'Source name',
      kind: 'Kind',
      fuel: 'Fuel or material (optional)',
      meterOrSupplier: 'Meter or supplier (optional)',
      contractorOperated: 'Operated by a contractor (its emissions default to scope 3)',
      code: 'Code',
      label: 'Label',
      oneUnitEquals: 'One unit equals',
      of: 'Of',
      material: 'Material',
      kgPerLitre: 'kg per litre',
      source: 'Source',
      factorName: 'Name',
      suggestedScope: 'Suggested scope',
      category: 'Category',
      unit: 'Unit',
      kgCo2ePerUnit: 'kg CO₂e per unit',
      hfcsKgPerUnit: 'HFCs kg per unit (optional)',
      blendComposition: 'Blend composition (optional)',
      gwpBasis: 'GWP basis of the published figure',
      factorSource: 'Source (publication, table, data year)',
      publicationYear: 'Publication year',
      dataYear: 'Data year',
      validTo: 'Valid to',
      searchFactors: 'Search factors',
    },
    dialog: {
      newOrganization: 'New organization',
      deleteOrganization: 'Delete organization',
      addEntity: 'Add legal entity',
      editEntity: 'Edit legal entity',
      addFacility: 'Add facility',
      addFactor: 'Add an emission factor',
    },
    option: {
      memberRole: {
        OWNER: 'Owner',
        REVIEWER: 'Reviewer (approves and publishes)',
        PREPARER: 'Preparer (records, classifies, runs)',
        VERIFIER: 'Verifier (read-only)',
      } as Record<string, string>,
      roleShort: { OWNER: 'Owner', REVIEWER: 'Reviewer', PREPARER: 'Preparer', VERIFIER: 'Verifier' } as Record<string, string>,
      relationship: {
        SUBSIDIARY: 'Group company or subsidiary (financial control)',
        ASSOCIATE: 'Associate or affiliate (significant influence, no control)',
      } as Record<string, string>,
      lease: { OPERATING_LEASE_IN: 'Operating lease (leased in)' } as Record<string, string>,
      kind: {
        STATIONARY_COMBUSTION: 'Stationary combustion',
        MOBILE_COMBUSTION: 'Mobile combustion',
        PURCHASED_ELECTRICITY: 'Purchased electricity',
      } as Record<string, string>,
    },
    text: {
      yourRole: 'Your role:',
      readOnlyBanner: 'Your role in this organization is Verifier (read-only).',
      writeTooltip: 'Needs the Preparer, Reviewer or Owner role.',
      approved: 'Approved',
      notApproved: 'Not approved',
      selfApproved: '(self-approved: nobody else could check it)',
      typicalValue: 'Typical value',
      history: 'History',
      ownFactors: "This organization's factors",
    },
  },
  act: {
    button: {
      import: 'Import',
      addRecords: 'Add records',
      assignSource: 'Assign emission source',
      assign: 'Assign',
      setTier: 'Set data quality tier',
      addEvidenceLink: 'Add evidence link',
      downloadTemplate: 'Download CSV template',
      addActivity: '+ Add activity',
      save: 'Save',
      saveDraft: 'Save draft',
      addLink: 'Add link',
      remove: 'Remove',
      downloadIndex: 'Download evidence index (CSV)',
    },
    field: {
      spreadsheetFile: 'Spreadsheet file',
      whyThisSource: 'Why this source?',
      kind: 'Kind',
      activityType: 'Activity type *',
      facility: 'Facility *',
      quantity: 'Activity quantity *',
      periodStart: 'Period start *',
      periodEnd: 'Period end',
      documentReference: 'Document reference',
      reason: 'Reason for the correction *',
      emissionSource: 'Emission source',
      newSourceName: 'Source name *',
      whyDifferentSource: 'Why is this a different source?',
      attachFile: 'Attach a file',
      linkName: 'Link name',
      url: 'URL',
      search: 'Search',
    },
    dialog: {
      import: 'Import activity data',
    },
    option: {
      newEmissionSource: 'New emission source…',
    },
    tab: {
      activity: 'Activity',
      evidence: 'Evidence',
    },
    text: {
      controlTotals: 'Control totals',
      recordsToAdd: 'Records to add',
      needsDecision: 'Needs a decision',
      decideUnknown: 'Decide',
      addedDuringImport: 'added during import',
      removeSourceDialog: 'Remove emission source?',
      supportingEvidence: 'Supporting evidence',
      resolve: 'Resolve',
      noSource: 'No emission source',
      ready: 'Ready',
    },
  },
  inv: {
    button: {
      newInventory: 'New inventory',
      createInventory: 'Create inventory',
      saveChanges: 'Save changes',
      cancel: 'Cancel',
      open: 'Open',
      editInventory: 'Edit inventory',
      saveDeclaration: 'Save declaration',
      reviewActivityData: 'Review activity data',
      freezeInventory: 'Freeze inventory',
    },
    field: {
      name: 'Name',
      periodStart: 'Period start',
      periodEnd: 'Period end',
      straddle: 'Records that straddle the period or a membership window',
      purpose: 'Purpose (optional)',
      approach: 'Consolidation approach',
      gwpSet: 'GWP set',
      prefillBoundary: 'Start with every operation the approach includes in the boundary',
      copyFrom: 'Copy the view from (optional)',
    },
    dialog: {
      newInventory: 'New inventory',
      editInventory: 'Edit inventory',
      freeze: 'Freeze the inventory?',
    },
    option: {
      approach: { EQUITY_SHARE: 'Equity share', FINANCIAL_CONTROL: 'Financial control', OPERATIONAL_CONTROL: 'Operational control' } as Record<string, string>,
      gwpSet: { AR5: 'AR5 (default)', AR6: 'AR6' } as Record<string, string>,
      straddle: { PRO_RATE: 'Pro-rate by days (default)', BLOCK: 'Block the run until the record is split' } as Record<string, string>,
      whyLeftOut: 'Why is it left out?',
    },
    text: {
      outsideUnder: 'Outside the boundary under',
      operationalBoundary: 'Operational boundary declaration',
      declarationSaved: 'Operational boundary declaration saved.',
    },
  },
  cls: {
    button: {
      chooseFactor: 'Choose factor…',
      changeFactor: 'Change factor…',
      exclude: 'Exclude',
      addRule: 'Add rule',
      addInstrument: 'Add instrument',
      saveInstrument: 'Save instrument',
      saveResidualMix: 'Save residual mix',
      reopen: 'Reopen as draft',
    },
    tab: { classify: 'Classify', exclude: 'Exclude' },
    field: {
      justification: 'Justification',
      reason: 'Reason',
      gas: 'Gas',
      estimated: 'Estimated emissions left out (kg CO₂e)',
      notEstimated: 'Not estimated',
      emitsNothing: 'This record emits nothing',
      narrowPrimary: 'Narrow the primary factors',
      primaryFactor: 'Primary factor',
      narrowUpstream: 'Narrow the upstream factors',
      upstreamFactor: 'Upstream factor',
      kind: 'Kind',
      facility: 'Facility',
      instrument: 'Instrument',
      kgPerKwh: 'kg CO₂e per kWh',
      source: 'Source',
      coveredMwh: 'Covered quantity (MWh)',
      reference: 'Certificate or contract reference',
      registry: 'Registry',
      vintage: 'Vintage (year)',
      residualAvailable: 'Residual mix available',
      residualFactor: 'Residual mix, kg CO₂e per kWh',
      status: 'Status',
      showUnapproved: 'Show unapproved',
    },
    dialog: { reopen: 'Reopen as a draft?' },
    option: {
      scope: { SCOPE_1: 'Scope 1', SCOPE_2: 'Scope 2', SCOPE_3: 'Scope 3' } as Record<string, string>,
      instrument: {
        SUPPLIER_SPECIFIC: 'Supplier-specific factor',
        CONTRACT: 'Power purchase contract',
        CERTIFICATE: 'Energy attribute certificate',
        RESIDUAL_MIX: 'Residual mix',
      } as Record<string, string>,
      residual: { yes: 'Yes, an adjusted residual mix is published', no: 'No residual mix is available' },
    },
    text: {
      included: 'Included',
      unclassified: 'Unclassified',
      notApplied: 'Not applied',
      suggested: "Suggested for this facility's grid",
      frozen: 'Frozen. The boundary and the activity view are read-only and runs are allowed.',
    },
  },
  run: {
    button: {
      launch: 'Launch calculation run',
      voidEllipsis: 'Void…',
      voidRun: 'Void run',
      markFinal: 'Mark as final',
      withdrawFinal: 'Withdraw final designation',
      withdrawConfirm: 'Withdraw designation',
      publish: 'Publish',
      createCorrection: 'Create correction',
      addDenominator: 'Add denominator',
      saveHeader: 'Save report header',
      unapprove: 'Unapprove',
    },
    field: {
      runLabel: 'Run label',
      reviewNote: 'Review note (optional)',
      correctionReason: 'Reason for the correction',
      approvedBy: 'Approved by (optional)',
      uncertainty: 'Uncertainty statement',
      denominator: 'Denominator',
      value: 'Value',
      dataSource: 'Data source',
    },
    dialog: {
      withdraw: 'Withdraw the final designation?',
      publish: 'Publish the inventory?',
      correction: 'Create a correction',
    },
    text: {
      cameFrom: 'Where this inventory came from',
      changedSincePublication: 'Changed since publication:',
      published: 'Published. The runs are a record; a correction restates the year.',
      writeTooltip: 'Needs the Reviewer or Owner role.',
      recalculate: 'A published inventory cannot be recalculated. Create a correction that supersedes it.',
      reportVersion: 'Report version',
    },
  },
  pack: {
    nav: { factorPacks: 'Factor packs', organizations: 'Organizations', updates: 'Updates' },
    button: {
      clone: 'Clone',
      createDraft: 'Create draft',
      edit: 'Edit',
      saveRow: 'Save row',
      publish: 'Publish',
      deleteDraft: 'Delete draft',
      blastRadius: 'Blast radius',
      withdraw: 'Withdraw',
      withdrawEdition: 'Withdraw edition',
      review: 'Review',
      view: 'View',
      accept: 'Accept',
      decline: 'Decline',
      assumeAccess: 'Assume access',
      endAccess: 'End access',
      endSupportAccessTo: 'End support access to',
    },
    field: {
      editionId: 'Edition identifier',
      appliesFrom: 'Applies from',
      code: 'Code',
      unit: 'Unit',
      kgCo2e: 'kg CO2e per unit',
      dataYear: 'Data year',
      sourceDocument: 'Source document',
      sourceCited: 'Source document as cited',
      whyWithdrawn: 'Why it is withdrawn',
      reason: 'Reason',
      answer: 'How does chapter 5 treat this adoption?',
      note: 'Note (optional)',
    },
    tab: { rows: 'Rows', metadata: 'Metadata', validation: 'Validation', changes: 'Changes' },
    rule: {
      code: 'The code names the publication and the row',
      provenance: 'The provenance is complete',
      unit: 'The unit is one the registry knows',
    } as Record<string, string>,
    text: {
      everyRulePasses: 'Every rule passes',
      rulesPass: 'Every publication rule passes.',
      noDocument: 'No source document yet. Upload the publication this edition was transcribed from.',
      noDate: 'Give the date the edition applies from. It is the vintage boundary an adoption is run from.',
      curatorGate: 'The approver must not be the curator. You built this draft, so another administrator checks it against the source document and publishes it.',
      checksum: 'computed over the bytes stored',
      publishedImmutable: 'This edition is published, so its rows, metadata and values never change again',
      noOrganization: 'No organization',
      whatMoves: 'What moves',
      earlierPeriods: 'Earlier periods',
      diffHash: 'Diff hash',
      noBaseYear: 'The organization has no base year, so no recalculation candidate can be raised.',
      decliningStays: 'Declining stays available.',
      nothingToDecide: 'The publisher withdrew this edition, so there is nothing to decide.',
      underSupportAccess: 'under support access',
      supportAccess: 'Support access',
      holdsOne: 'one of these lineages',
      lockedPeriod: 'Inside a locked period',
      updateWaiting: 'factor pack update',
    },
  },
  base: {
    section: 'Baseline and targets',
    button: {
      designate: 'Designate base year',
      savePolicy: 'Save policy',
      raise: 'Raise a candidate',
      raiseConfirm: 'Raise',
      recordBase: 'Record recalculated base',
      record: 'Record',
      decline: 'Decline',
      deleteFactor: 'Delete factor',
      delete: 'Delete',
    },
    field: {
      inventory: 'Base-year inventory',
      threshold: 'Significance threshold (%)',
      reason: 'Why this year',
      convention: 'Mid-year structural changes',
      trigger: 'Trigger',
      whatChanged: 'What changed',
      share: 'Affected share of base-year emissions (%)',
      comparisonRun: 'Comparison run id (optional)',
      baseRun: 'Recalculated base run',
      note: 'Note (optional)',
    },
    dialog: {
      raise: 'Raise a recalculation candidate',
      decline: 'Decline the recalculation?',
      record: 'Record the recalculated base year',
    },
    option: {
      convention: {
        TRANSACTION_DATE: 'From the transaction date (membership windows)',
        WHOLE_YEAR: 'For the whole year, as the Standard recommends',
      } as Record<string, string>,
      trigger: { METHODOLOGY_CHANGE: 'Methodology change', ERROR_CORRECTION: 'Significant error corrected' } as Record<string, string>,
    },
    text: {
      ofBaseYear: 'of base-year emissions',
      baseRun: 'Base-year run:',
      recalculatedBase: 'recalculated base:',
      holdsFinal: 'Base year holds the final designation; runs stay available.',
      differentGwp: 'This run and the base year use different GWP sets',
      recordsKept: 'Publish records are kept',
    },
  },
  historySetting: {
    supportAccessWindowHours: 'Support access window',
    organizationCreation: 'Who may create an organization',
    editionsInPublishedPeriods: 'Editions inside a published period',
  } as Record<string, string>,
} as const

/** Every string of the surface, flattened, for lint. */
export function surfaceStrings(): Array<{ path: string; value: string }> {
  const out: Array<{ path: string; value: string }> = []
  const walk = (node: unknown, path: string) => {
    if (typeof node === 'string') out.push({ path, value: node })
    else if (node && typeof node === 'object')
      for (const [k, v] of Object.entries(node)) walk(v, path ? `${path}.${k}` : k)
  }
  walk(S, '')
  return out
}

/** "2 hours", "1 hour": how the settings page and its history print the window. */
export function hoursLabel(hours: number | string): string {
  return `${hours} ${String(hours) === '1' ? 'hour' : 'hours'}`
}

/** A setting's value as the form and the history show it. */
export function settingValueLabel(setting: string, value: string | number): string {
  if (setting === 'supportAccessWindowHours') return hoursLabel(value)
  if (setting === 'organizationCreation') return S.option.organizationCreation[String(value)] ?? String(value)
  if (setting === 'editionsInPublishedPeriods') return S.option.editions[String(value)] ?? String(value)
  return String(value)
}

/** "1 access request waiting", as the dashboard's queue puts it. */
export function accessRequestsWaiting(count: number): string {
  return `${count} ${S.text.accessRequest}${count === 1 ? '' : 's'} waiting`
}
