-- Spec 09: what the help centre records so we can tell whether it works.
-- Three tables and no reader identity anywhere: a vote carries a salted hash
-- that exists only to keep one vote per voter per article, a missed search is
-- kept as its normalized text and a count, and the per-day counters give the
-- miss rate its denominator. A nightly job trims each table to its retention.

-- 1. Was this helpful? One row per (article, voter); a changed vote replaces
--    the earlier one. The reason travels only with a No.
CREATE TABLE help_feedback (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_slug   varchar(160) NOT NULL,
    helpful     boolean      NOT NULL,
    reason      varchar(20)  CHECK (reason IN ('NOT_ACCURATE', 'NOT_CLEAR', 'NOT_RELEVANT')),
    comment     varchar(500),
    voter_hash  char(64)     NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT chk_help_feedback_reason_only_with_no
        CHECK (helpful = false OR reason IS NULL),
    CONSTRAINT uq_help_feedback_page_voter
        UNIQUE (page_slug, voter_hash)
);

-- the per-article listing and the recent-comments view both read newest first
CREATE INDEX idx_help_feedback_page_created ON help_feedback (page_slug, created_at DESC);

-- 2. Searches that found nothing, as the normalized query and how often.
--    Successful searches are never stored.
CREATE TABLE help_search_misses (
    query_normalized varchar(120) PRIMARY KEY,
    count            integer      NOT NULL DEFAULT 1,
    first_seen       timestamptz  NOT NULL DEFAULT now(),
    last_seen        timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_help_search_misses_last_seen ON help_search_misses (last_seen DESC);

-- 3. One row per day: every search counts, so the miss rate has a denominator.
CREATE TABLE help_search_days (
    day       date    PRIMARY KEY,
    searches  integer NOT NULL DEFAULT 0,
    misses    integer NOT NULL DEFAULT 0
);
